wip

diff --git a/.install b/.install
--- a/.install
+++ b/.install
@@ -17,7 +17,8 @@ while read path; do
     echo -e "$(green ✔) $(cyan "$bin") is already installed ($(yellow "v$(version "$bin")"))"
   else
     echo "Installing $(cyan "$bin")... "
-    "$path"
-    echo "$(green ✔) $(cyan "$bin") $(green installed successfully) ($(yellow "v$(version "$bin")"))"
+    "$path" \
+      && echo "$(green ✔) $(cyan "$bin") $(green installed successfully) ($(yellow "v$(version "$bin")"))" \
+      || echo "$(red ✘ Failed installing) $(red_light "$bin")"
   fi
 done < <(find "$HOME/.install.d" -type f)
