Fixed commit-message git alias

diff --git a/.dotfiles/profile.d/git b/.dotfiles/profile.d/git
--- a/.dotfiles/profile.d/git
+++ b/.dotfiles/profile.d/git
@@ -1,5 +1,20 @@
 #!/usr/bin/env sh
 
+git_date() {
+  delta=${GIT_DATE-0}
+  if date --version 2>/dev/null | grep -q GNU
+  then
+    date --date="$delta days ago"
+  elif type -p gdate >/dev/null
+  then
+    gdate --date="$delta days ago"
+  else
+    echo "GNU date is required, please run:" >&2
+    echo "brew install coreutils" >&2
+    return 1
+  fi
+}
+
 # Get the current local branch name, even when rebasing/merging
 git_current_local_branch() {
   branch="$(git rev-parse --abbrev-ref HEAD)"
